var json_NYUGlobalSites_3 = {
"type": "FeatureCollection",
"name": "NYUGlobalSites_3",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Continent": "North America", "Location": "NYU Los Angeles", "Latitude": 34.07319532, "Longitude": -118.3617418, "Academic Approach": "Advanced students interested in pursuing careers in the entertainment and media industries who engage in rigorous academic coursework taught by industry professionals. All Students are required to enroll in the Experiential Learning Seminar which allows students the opportunity to pair their classroom experience with a meaningful internship opportunity, working 16-30 hours per week", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ -118.3617418, 34.07319532 ] } },
{ "type": "Feature", "properties": { "Continent": "North America", "Location": "NYU Washington DC", "Latitude": 38.90409558, "Longitude": -77.03037335, "Academic Approach": "Students engage deeply with politics, policy, business, journalism, and leadership through coursework and experiential learning in the nation�s capital.", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ -77.03037335, 38.90409558 ] } },
{ "type": "Feature", "properties": { "Continent": "Africa", "Location": "NYU Accra", "Latitude": 5.570338153, "Longitude": -0.173586444, "Academic Approach": "Interdisciplinary approach to Africana studies, study global public health, and explore urban and metropolitan studies", "Partnerships": "Center for the Study of the African Diaspora\n\nNYU Africa House\n\nNYU Center for Technology and Economic Development\n\nNYU Institute of African American Affairs" }, "geometry": { "type": "Point", "coordinates": [ -0.173586444, 5.570338153 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU Berlin", "Latitude": 52.53934769, "Longitude": 13.41226361, "Academic Approach": "Variety of offerings in the social sciences and humanities, with robust programming in environmental studies, politics, and sociology", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 13.41226361, 52.53934769 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU Florence", "Latitude": 43.79588105, "Longitude": 11.26183412, "Academic Approach": "Study Italy's history and its extraordinary art, literature, philosophy, and architecture, along with the political, cultural, economic and social issues that play a role in shaping Europe's future.", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 11.26183412, 43.79588105 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU London", "Latitude": 51.51950269, "Longitude": -0.129029551, "Academic Approach": " Course offerings in business, international relations, literature and theatre, psychology, and Africana studies.  Prehealth students can find all the science, technology, engineering, and mathematics (STEM) courses", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ -0.129029551, 51.51950269 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU Madrid", "Latitude": 40.42159221, "Longitude": -3.695708006, "Academic Approach": "Students of Spanish language and culture gain fluency, art history enthusiasts study masterpieces at the Prado Museum, and business students learn about the European economy", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ -3.695708006, 40.42159221 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU Paris", "Latitude": 48.85049834, "Longitude": 2.346905724, "Academic Approach": "Explore French language and culture, engage with art and theatre, study media and philosophy, or deepen your musical and performance skills.", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 2.346905724, 48.85049834 ] } },
{ "type": "Feature", "properties": { "Continent": "Europe", "Location": "NYU Prague", "Latitude": 50.07363749, "Longitude": 14.43395439, "Academic Approach": "Programs in journalism and media as well as music�both performance and composition�offer unique learning opportunities programs in journalism and media as well as music�both performance and composition�offer unique learning opportunities", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 14.43395439, 50.07363749 ] } },
{ "type": "Feature", "properties": { "Continent": "Asia", "Location": "NYU Tel Aviv", "Latitude": 32.09325143, "Longitude": 34.78709181, "Academic Approach": "It is an ideal place to study not only politics and the Middle East but also emerging media and the sciences", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 34.78709181, 32.09325143 ] } },
{ "type": "Feature", "properties": { "Continent": "Australia", "Location": "NYU Sydney", "Latitude": -33.8619234, "Longitude": 151.2061457, "Academic Approach": "NYU Sydney offers all the benefits of being a full-time USYD student, and students may enroll in courses offered by both universities� curricula.", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ 151.2061457, -33.8619234 ] } },
{ "type": "Feature", "properties": { "Continent": "South America", "Location": "NYU Buenos Aires", "Latitude": -34.59379337, "Longitude": -58.40604652, "Academic Approach": "Focus on everything from global public health to media and Latin American studies to Spanish language acquisition while engaging in place-based coursework", "Partnerships": null }, "geometry": { "type": "Point", "coordinates": [ -58.40604652, -34.59379337 ] } }
]
}
